version: "3"
services:
  database:
    image: postgres:14.3-alpine
    container_name: pg_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      # - POSTGRES_HOST_AUTH_METHOD=trust # Login without password
    volumes:
      - ./pgsql_mount:/var/lib/postgresql/data
      - ./scripts/:/docker-entrypoint-initdb.d/
